-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- SENDER Table Create SQL
CREATE TABLE SENDER
(
    SPID_ID     INT            NOT NULL    AUTO_INCREMENT, 
    SPID_DEPT   VARCHAR(45)    NULL, 
    SPID_NAME   VARCHAR(45)    NULL, 
    SPID_TEL1   VARCHAR(45)    NULL, 
    SPID_TEL2   VARCHAR(45)    NULL, 
    SPID_EMAIL  VARCHAR(45)    NULL, 
    JOB         VARCHAR(45)    NULL, 
    PRIMARY KEY (SPID_ID)
);


-- VENDER Table Create SQL
CREATE TABLE VENDER
(
    VENDER_ID    INT            NOT NULL    AUTO_INCREMENT, 
    VENDER_NAME  VARCHAR(45)    NULL, 
    SPID_ID      INT            NULL, 
    PRIMARY KEY (VENDER_ID)
);

ALTER TABLE VENDER
    ADD CONSTRAINT FK_VENDER_SPID_ID_SENDER_SPID_ID FOREIGN KEY (SPID_ID)
        REFERENCES SENDER (SPID_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TOOL Table Create SQL
CREATE TABLE TOOL
(
    TOOL_ID            INT             NOT NULL    AUTO_INCREMENT, 
    TOOL_NAME          VARCHAR(100)    NULL, 
    TOOL_MODEL_NUMBER  VARCHAR(45)     NULL, 
    TOOL_LICENSE       VARCHAR(45)     NULL,
    VENDER_ID          INT             NULL, 
    TOOL_DETAILS       VARCHAR(200)    NULL, 
    PRIMARY KEY (TOOL_ID)
);

ALTER TABLE TOOL
    ADD CONSTRAINT FK_TOOL_VENDER_ID_VENDER_VENDER_ID FOREIGN KEY (VENDER_ID)
        REFERENCES VENDER (VENDER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- ESTIMATE Table Create SQL
CREATE TABLE ESTIMATE
(
    ESTIMATE_ID     INT             NOT NULL    AUTO_INCREMENT, 
    TITLE           VARCHAR(45)     NULL, 
    COMPANY         VARCHAR(45)     NULL, 
    INCHARGE        VARCHAR(45)     NULL, 
    TEL             VARCHAR(45)     NULL, 
    EMAIL           VARCHAR(45)     NULL, 
    SPID_ID         INT             NULL, 
    ESTIMATE_DATE   DATETIME        NULL, 
    ESTIMATE_NOTE   VARCHAR(300)    NULL, 
    PRIMARY KEY (ESTIMATE_ID)
);

ALTER TABLE ESTIMATE
    ADD CONSTRAINT FK_ESTIMATE_SPID_ID_SENDER_SPID_ID FOREIGN KEY (SPID_ID)
        REFERENCES SENDER (SPID_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- PRICE Table Create SQL
CREATE TABLE PRICE
(
    PRICE_ID       INT      NOT NULL    AUTO_INCREMENT, 
    KRW            FLOAT    NULL, 
    EXCHANGE_RATE  FLOAT    NULL, 
    TOOL_ID        INT      NULL, 
    EUR            FLOAT    NULL, 
    QUANTITY       INT      NULL        DEFAULT 1, 
    PRIMARY KEY (PRICE_ID)
);

ALTER TABLE PRICE
    ADD CONSTRAINT FK_PRICE_TOOL_ID_TOOL_TOOL_ID FOREIGN KEY (TOOL_ID)
        REFERENCES TOOL (TOOL_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- ESTIMATE_DETAIL Table Create SQL
CREATE TABLE ESTIMATE_DETAIL
(
    ESTIMATE_DETAIL_ID  INT             NOT NULL    AUTO_INCREMENT, 
    ESTIMATE_DETAILS    VARCHAR(200)    NULL, 
    QUANTITY            INT             NULL, 
    UNIT                VARCHAR(45)     NULL, 
    UNIT_PRICE          INT             NULL, 
    SUPPLY_PRICE        INT             NULL, 
    ESTIMATE_ID         INT             NULL, 
    DISCOUNT_RATE       INT             NULL, 
    PRIMARY KEY (ESTIMATE_DETAIL_ID)
);

ALTER TABLE ESTIMATE_DETAIL
    ADD CONSTRAINT FK_ESTIMATE_DETAIL_ESTIMATE_ID_ESTIMATE_ESTIMATE_ID FOREIGN KEY (ESTIMATE_ID)
        REFERENCES ESTIMATE (ESTIMATE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
